#!/bin/sh

<<COPYRIGHT

Copyright (C) 2010 Antonio Anselmi <tony.anselmi@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of version 2 of the GNU General Public
License as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file.  If not, see <http://www.gnu.org/licenses/>.

COPYRIGHT

# /sbin/REBOOT

[ -z "$1" ] &&	AGENT="/sbin/reboot" || AGENT="/sbin/do_reboot :$1"
echo "< reboot requested by $AGENT" >> /etc/boots.log

find_mtd_part() {
	local PART="$(grep "\"$1\"" /proc/mtd | awk -F: '{print $1}')"
	local PREFIX=/dev/mtdblock
	
	PART="${PART##mtd}"
	[ -d /dev/mtdblock ] && PREFIX=/dev/mtdblock/
	echo "${PART:+$PREFIX$PART}"
}

jffs2_ready () {
	mtdpart="$(find_mtd_part rootfs_data)"
	magic=$(hexdump $mtdpart -n 4 -e '4/1 "%02x"')
	[ "$magic" != "deadc0de" ]
}

grep rootfs_data /proc/mtd >/dev/null 2>/dev/null && {
	while true; do
		jffs2_ready && break #jffs2 ready
		sleep 1 #jffs2 not ready yet; wait
	done
} 

# Newer models of the EOC-1650 and Ubiquiti devices will lock up on reboot
# if the shutdown init scripts fail to complete.  So go straight for an
# immediate reboot.  Also, avoid attempting to kill the init process,
# this can cause lockup on EOC reboots as well.
busybox reboot -f
