#!/bin/sh
#captive_portal

echo "checking captive portal..." 
cp_HANDLER=$(uci get cp_switch.main.which_handler)

[ "$cp_HANDLER" -gt 0 ] && {
	max_threads=$(uci get cp_switch."handler_${cp_HANDLER}".max_threads)
	REASON=35

	case $cp_HANDLER in
		1) threads=$(INSTANCES nodogsplash) ;;
		4|5|6) threads=$(INSTANCES chilli)  ;;
	esac

	if [ "$max_threads" -gt 0 ] ; then
		[ "$threads" -gt "$max_threads" ] && /sbin/do_reboot $REASON 
	fi
	[ "$threads" -eq 0 ] && /sbin/do_reboot $REASON 
}
#
